export const sermons = [
	{
		id: 1,
		title: "New Testament Examples –  ",
		series: "Standalone",
		speaker: "Pastor Steven Jason",
		topic: "New Testament Examples",
		date: "2024-06-16",
		scripture: "Matthew 16:13-19",
		thumbnail: "https://i.ytimg.com/vi/c-QQ2ePp2LQ/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/c-QQ2ePp2LQ",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
		description:
			"In Part 4 of this powerful series, Pastor Steven Jason unpacks how ordinary people in the New Testament displayed extraordinary faith—not in themselves, but in God. Their stories challenge and inspire us to walk in unshakable confidence, rooted in God’s power and promises.",
	},
	{
		id: 2,
		title: "Mary – Accepting God’s Plan",
		series: "Made to Multiply",
		speaker: "Pastor Steven Jason",
		topic: "New Testament Examples",
		date: "2024-06-09",
		scripture: "Genesis 1:26-28",
		thumbnail: "https://i.ytimg.com/vi/SozNnuIulRY/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/SozNnuIulRY",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
		description:
			" Pastor Steven Jason unpacks how ordinary people in the New Testament displayed extraordinary faith—not in themselves, but in God. Their stories challenge and inspire us to walk in unshakable confidence, rooted in God’s power and promises.",
	},
	{
		id: 3,
		title: "The essence of the church",
		series: "the essence of the body of christ",
		speaker: "Pastor Steven Jason",
		topic: "church",
		date: "2024-05-26",
		scripture: "Genesis 2:19-20",
		thumbnail: "https://i.ytimg.com/vi/jKGWYscUofo/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/jKGWYscUofo",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
		description: "Biblical principles for godly masculinity and leadership.",
	},
	{
		id: 4,
		title: "The essence of the church",
		series: "the essence of the body of christ",
		speaker: "Pastor Steven Jason ",
		topic: "Womanhood",
		date: "2024-05-19",
		scripture: "Genesis 2:18-23 & 3:20",
		thumbnail: "https://i.ytimg.com/vi/Krzhcq48YOs/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/Krzhcq48YOs",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
		description: "God's design for women and their vital role in His kingdom.",
	},
	{
		id: 5,
		title: "Multiply in Marriage // Genesis 2:21-25",
		series: "Made to Multiply",
		speaker: "Pastor Josh Howerton",
		topic: "Marriage",
		date: "2024-05-12",
		scripture: "Genesis 2:21-25",
		thumbnail: "https://i.ytimg.com/vi/BVKhVj5PI1A/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/BVKhVj5PI1A",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
		description: "Building Christ-centered marriages that reflect God's love.",
	},
	{
		id: 6,
		title: "Multiplication & Temptation // Genesis 3:1-21",
		series: "Made to Multiply",
		speaker: "Pastor Josh Howerton",
		topic: "Temptation",
		date: "2024-05-05",
		scripture: "Genesis 3:1-21",
		thumbnail: "https://i.ytimg.com/vi/QbIqFmk0jcs/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/QbIqFmk0jcs",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
		description: "Overcoming temptation through the power of Christ.",
	},
	{
		id: 7,
		title: "Multiplication & Sacrifice // Genesis 3:22-4:16",
		series: "Made to Multiply",
		speaker: "Pastor Michael Smith",
		topic: "Sacrifice",
		date: "2024-04-28",
		scripture: "Genesis 3:22-4:16",
		thumbnail: "https://i.ytimg.com/vi/e2x1QBivqkM/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/e2x1QBivqkM",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
		description: "The power of living a sacrificial life for Christ.",
	},
	{
		id: 8,
		title: "Multiplication Effect of Sin & Blessing // Genesis 4:17-6:18",
		series: "Made to Multiply",
		speaker: "Pastor Josh Howerton",
		topic: "Sin and Blessing",
		date: "2024-04-21",
		scripture: "Genesis 4:17-6:18",
		thumbnail: "https://i.ytimg.com/vi/JdecgbY7Abk/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/JdecgbY7Abk",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
		description:
			"Understanding how sin spreads and how God's blessing multiplies.",
	},
	{
		id: 9,
		title: "Arks & Altars // Genesis 6:1-8:22",
		series: "Made to Multiply",
		speaker: "Pastor Sarah Johnson",
		topic: "Faith",
		date: "2024-04-14",
		scripture: "Genesis 6:1-8:22",
		thumbnail: "https://i.ytimg.com/vi/7MBZkFdgKUI/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/7MBZkFdgKUI",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
		description: "Building your life on the foundation of faith in God.",
	},
	{
		id: 10,
		title: "What Are You Looking For? // Genesis 11:1-9",
		series: "Made to Multiply",
		speaker: "Pastor Josh Howerton",
		topic: "Purpose",
		date: "2024-04-07",
		scripture: "Genesis 11:1-9",
		thumbnail: "https://i.ytimg.com/vi/hXyzt0wKcRY/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/hXyzt0wKcRY",
		audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
		description: "Discovering God's purpose for your life in Christ.",
	},
];
