export const sermons = [
	{
		id: 1,
		title: "New Testament Examples –  ",
		series: "New Testament Examples",
		speaker: "Pastor Steven Jason",
		topic: "New Testament Examples",
		date: "2024-06-16",
		scripture: "Matthew 16:13-19",
		thumbnail: "https://i.ytimg.com/vi/c-QQ2ePp2LQ/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/c-QQ2ePp2LQ",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description:
			"In Part 4 of this powerful series, Pastor Steven Jason unpacks how ordinary people in the New Testament displayed extraordinary faith—not in themselves, but in God. Their stories challenge and inspire us to walk in unshakable confidence, rooted in God’s power and promises.",
	},
	{
		id: 2,
		title: "Mary – Accepting God’s Plan",
		series: "New Testament Examples",
		speaker: "Pastor Steven Jason",
		topic: "New Testament Examples",
		date: "2024-06-09",
		scripture: "Genesis 1:26-28",
		thumbnail: "https://i.ytimg.com/vi/SozNnuIulRY/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/SozNnuIulRY",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description:
			" Pastor Steven Jason unpacks how ordinary people in the New Testament displayed extraordinary faith—not in themselves, but in God. Their stories challenge and inspire us to walk in unshakable confidence, rooted in God’s power and promises.",
	},
	{
		id: 3,
		title: "The essence of the church",
		series: "the essence of the body of christ",
		speaker: "Pastor Steven Jason",
		topic: "church",
		date: "2024-05-26",
		scripture: "Genesis 2:19-20",
		thumbnail: "https://i.ytimg.com/vi/jKGWYscUofo/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/jKGWYscUofo",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description: "Biblical principles for godly masculinity and leadership.",
	},
	{
		id: 4,
		title: "The essence of the church",
		series: "the essence of the body of christ",
		speaker: "Pastor Steven Jason ",
		topic: "the Church",
		date: "2024-05-19",
		scripture: "Genesis 2:18-23 & 3:20",
		thumbnail: "https://i.ytimg.com/vi/Krzhcq48YOs/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/Krzhcq48YOs",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description: "God's design for women and their vital role in His kingdom.",
	},
	{
		id: 5,
		title: "Revival",
		series: "Revival",
		speaker: "Pastor Steven Jason",
		topic: "Revival",
		date: "2024-05-12",
		scripture: "Genesis 2:21-25",
		thumbnail: "https://i.ytimg.com/vi/BVKhVj5PI1A/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/BVKhVj5PI1A",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description:
			"A church committed to bring deliverance, restoration, revival and healing to all people. Teaching them to have a purpose driven life in Christ Jesus.",
	},
	{
		id: 6,
		title: "The Good Samaritan",
		series: "The Good Samaritan",
		speaker: "Pastor Steven Jason",
		topic: "The Good Samaritan",
		date: "2024-05-05",
		scripture: "Genesis 3:1-21",
		thumbnail: "https://i.ytimg.com/vi/QbIqFmk0jcs/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/QbIqFmk0jcs",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description: "Overcoming temptation through the power of Christ.",
	},
	{
		id: 7,
		title: "Diligence",
		series: "Diligence",
		speaker: "Pastor Steven Jason",
		topic: "Diligence",
		date: "2024-04-28",
		scripture: "Genesis 3:22-4:16",
		thumbnail: "https://i.ytimg.com/vi/e2x1QBivqkM/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/e2x1QBivqkM",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description: "The power of living a sacrificial life for Christ.",
	},
	{
		id: 8,
		title: "Godfidence",
		series: "Godfidence",
		speaker: "Pastor Steven Jason",
		topic: "God Confidence",
		date: "2024-04-21",
		scripture: "Genesis 4:17-6:18",
		thumbnail: "https://i.ytimg.com/vi/JdecgbY7Abk/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/JdecgbY7Abk",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description:
			"Understanding how sin spreads and how God's blessing multiplies.",
	},
	{
		id: 9,
		title: "Godfidence: Practical Examples",
		series: "Godfidence: Practical Examples",
		speaker: "Pastor Steven Jason",
		topic: "Godfidence",
		date: "2024-04-14",
		scripture: "Genesis 6:1-8:22",
		thumbnail: "https://i.ytimg.com/vi/7MBZkFdgKUI/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/7MBZkFdgKUI",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description: "Building your life on the foundation of faith in God.",
	},
	{
		id: 10,
		title: "Godfidence:The Pilot Message",
		series: "Godfidence",
		speaker: "Pastor Steven Jason",
		topic: "Godfidence",
		date: "2025-05-07",
		scripture: "Genesis 11:1-9",
		thumbnail: "https://i.ytimg.com/vi/hXyzt0wKcRY/maxresdefault.jpg",
		videoUrl: "https://www.youtube.com/embed/hXyzt0wKcRY",
		audioUrl: "https://open.spotify.com/show/6BHs8lkgFdLRTG30O1gMBw",
		description: "Discovering God's purpose for your life in Christ.",
	},
];
