import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link
					href='https://fonts.googleapis.com/css2?family=Lobster&family=Redressed&family=Shizuru&family=Open+Sans&family=Architects+Daughter&family=Yanone+Kaffeesatz&family=Roboto&display=swap'
					rel='stylesheet'
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
